
// GENERATED FILE - DO NOT MODIFY
// SEE https://github.com/usvc/go-generate-version for more information
//
// GENERATED BY GO:GENERATE AT 2019-12-19T09:27:14&#43;0800
//
// FILE GENERATED USING ~/generators/versioning/main.go

package main

// Version stores the latest git tag
const Version = "v0.3.22"

// Commit stores the commit SHA hash
const Commit = "ef0adc8"

