
// GENERATED FILE - DO NOT MODIFY
// SEE https://github.com/usvc/go-generate-version for more information
//
// GENERATED BY GO:GENERATE AT 2019-07-07T01:22:11&#43;0800
//
// FILE GENERATED USING ~/generators/versioning/main.go

package main

// Version stores the latest git tag
const Version = "v0.2.2"

// Commit stores the commit SHA hash
const Commit = "c7e2d83"

