
// GENERATED FILE - DO NOT MODIFY
// SEE https://github.com/usvc/go-generate-version for more information
//
// GENERATED BY GO:GENERATE AT 2019-07-07T15:56:54&#43;0800
//
// FILE GENERATED USING ~/generators/versioning/main.go

package main

// Version stores the latest git tag
const Version = "v0.3.2"

// Commit stores the commit SHA hash
const Commit = "f4cf49a"

